######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 3 22:26:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += classicProblem.h math.h string.h \
    graph.h
SOURCES += classicProblem.cpp math.cpp string.cpp test.cpp \
    graph.cpp
