######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 4 17:49:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += genericFunction.h
SOURCES += main.cpp
